### ISSUE TITLE
Integración continua

### ISSUE THREAD

**Issue by juanmiguelruiz** [mansancab3/decide-io-autenticacion#2]
---
name: Integración continua.
about: Integrar Travis en el proyecto.

---

El repositorio necesita integración continua para poder desplegar el proyecto y hacer pruebas de forma remota.

**Comment by aleromlop** [comment]
Ya está subido el .travis.yml   @juanmiguelruiz

**Comment by juanmiguelruiz** [comment]
Alex ya ha subido el archivo .yml que enlaza con Travis CI
